# Домашнее задание «Библиотека numpy. Вычислительные задачи»

## Преподаватель: Константин Башевой

## Домашнее задание

### Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [3]:
import numpy as np

In [7]:
A = np.arange(0,10)
A = np.flip(A)

In [8]:
A

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [35]:
N = 5

In [36]:
A = np.diag(np.arange(N,0, -1), k=1)

In [37]:
A

array([[0, 5, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0]])

In [38]:
# Ответ:
A.sum()

15

### Задание 3

Решите систему уравнений:  
4x + 2y + z = 4  
x + 3y = 12  
5y + 4z = -3  

In [26]:
from numpy import linalg 

In [22]:
A = np.array([[4,2,1],[1,3,0],[0,5,4]])
A

array([[4, 2, 1],
       [1, 3, 0],
       [0, 5, 4]])

In [24]:
b = np.array([[4],[12],[-3]])
b

array([[ 4],
       [12],
       [-3]])

In [28]:
A_inv = linalg.inv(A)
A_inv

array([[ 0.26666667, -0.06666667, -0.06666667],
       [-0.08888889,  0.35555556,  0.02222222],
       [ 0.11111111, -0.44444444,  0.22222222]])

In [31]:
X = np.dot(A_inv, b)

In [33]:
#  Ответ:
X

array([[ 0.46666667],
       [ 3.84444444],
       [-5.55555556]])

### Задание 4

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [62]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [63]:
# На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [64]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [65]:
angle_min = 360
closest_user_id = 0

for user_id in range(len(users_stats)):
    
    angle = np.arccos( cosine( users_stats[user_id], next_user_stats ) ) * 360 / 2 / np.pi
    if angle < angle_min:
        angle_min = angle
        closest_user_id = user_id
        

In [66]:
# Ответ:
print("ID самого похожего пользователя -" , closest_user_id)

ID самого похожего пользователя - 7
